project:
  type: website
  output-dir: _build/html

website:
  title: "ccp"
  favicon: _static/favicon.ico
  navbar:
    logo: _static/ccp.png
    left:
      - text: Getting Started
        menu:
          - text: Overview
            href: getting_started/overview.qmd
          - text: Installation
            href: getting_started/installation.qmd
      - text: User Guide
        menu:
          - text: Tutorial
            href: user_guide/tutorial.qmd
          - text: Engauge Digitizer
            href: user_guide/engauge.qmd
          - text: Polytropic Methods
            href: user_guide/polytropic_methods.ipynb
          - text: Evaluation Tutorial
            href: user_guide/evaluation_tutorial.ipynb
      - text: App Guide
        menu:
          - text: Straight-Through User Guide
            href: app_guide/straight_through_user_guide.qmd
          - text: Building Portable Executable
            href: app_guide/building_portable_exe.qmd
      - text: API Reference
        menu:
          - text: API Reference
            href: references/api.qmd
          - text: State
            href: references/State.qmd
          - text: Point
            href: references/Point.qmd
          - text: Impeller
            href: references/Impeller.qmd
          - text: Curve
            href: references/Curve.qmd
          - text: Plot Methods
            href: references/plot_methods.qmd
          - text: Performance Functions
            href: references/performance_functions.qmd
      - text: Contributing
        href: contributing.qmd
    right:
      - icon: github
        href: https://github.com/petrobras/ccp

format:
  html:
    theme: cosmo
    toc: true
    css: _static/custom.css

bibliography: references.bib

execute:
  freeze: true

quartodoc:
  package: ccp
  title: API Reference
  dir: references
  parser: numpy
  sections:
    - title: Core Classes
      desc: Main classes for compressor performance analysis.
      contents:
        - State
        - Point
        - Impeller
        - Curve
